### ISSUE TITLE
双击表格无法跳转到代码

### ISSUE THREAD

**Issue by zhoudu** [veezean/IntellijIDEA-CodeReview-Plugin#10]
IDEA 2022.2(Ultimate edition)
添加一行评审记录，切换到其他文件，然后双击该记录无法跳转到对应的代码行位置

**Comment by zhoudu** [comment]
问题更新：重新打开IDE，双击又可以跳转了

**Comment by veezean** [comment]
刚刚添加完的时候是不支持跳转的，除非该类被关掉然后重新打开。
