### ISSUE TITLE
编译过程中出错，显示窗口无信息

### ISSUE THREAD

**Issue by Secretceres** [veezean/IntellijIDEA-CodeReview-Plugin#22]
在runide过程中报错，并且提示 failed to init toolwindow；
![image](https://github.com/veezean/IntellijIDEA-CodeReview-Plugin/assets/96368985/8bf7b9a6-5a2c-46e4-83bb-de30e2a971af)
但是可以其中在启动的idea中发现窗口，但是窗口中没有信息。
![image](https://github.com/veezean/IntellijIDEA-CodeReview-Plugin/assets/96368985/f6906b54-0971-47a8-9131-0a3aaf657164)
Evemt log提示如下：
![image](https://github.com/veezean/IntellijIDEA-CodeReview-Plugin/assets/96368985/53235f28-f9eb-41fd-9a97-2529e570a78d)

**Comment by Secretceres** [comment]
添加配置文件之后已正常

**Comment by veezean** [comment]
好的，那issue先关掉了。
PS： 提交了重构后的新版本，支持自行配置修改需要的评审字段，提供了配套的新版服务端，欢迎试用。
